site_name: Deployment Helper Utility | DataHub
site_description: test

docs_dir: docs/

# Repository
repo_name: datax-tmp/datax-utils-deployment-helper
repo_url: https://github.com/datax-tmp/datax-utils-deployment-helper
edit_uri: ""

# Copyright
copyright: >
  Copyright &copy; 2022 - 2022 SCB DataX | Analytics & Product &hearts; DataHub
  <br><a href="#__consent", style="font-style: italic;">Change cookie settings</a>

#watch:
#  - src

plugins:
  - mike:
      version_selector: true
  - search:
      lang:
        - en
        - th
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
  - tags
  - mknotebooks:
      execute: false
      enable_default_pandas_dataframe_styling: true
      enable_default_jupyter_cell_styling: false
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_root_toc_entry: no
            docstring_style: google
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - table-reader

markdown_extensions:
  - abbr
  - codehilite
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format:
            !!python/name:pymdownx.superfences.fence_code_format ## TO DO: custom yaml tag IDE error


  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - attr_list
  - pymdownx.emoji:
      emoji_index:
        !!python/name:materialx.emoji.twemoji ## TO DO: custom yaml tag IDE error


      emoji_generator:
        !!python/name:materialx.emoji.to_svg ## TO DO: custom yaml tag IDE error


  - admonition
  - md_in_html
  - toc:
      permalink: True
      toc_depth: 2

extra:
  version:
    provider: mike
    default: latest
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - manage

extra_css:
  - overrides/stylesheets/extra.css
  - overrides/stylesheets/pandas-dataframe.css

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - overrides/javascripts/tablesort.js
  - overrides/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

theme:
  name: material
  custom_dir: docs/overrides
  language: en
  features:
    - search.suggest
    - search.highlight
    - search.share
    - navigation.tabs
    - navigation.tracking
    - content.code.annotate
    - navigation.top
  icon:
    repo: fontawesome/brands/git-alt
  palette:
    # Palette toogle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      accent: deep purple
      primary: white
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      accent: deep purple
      primary: white

# Page tree
nav:
  - Home: index.md
  - API Reference: reference/ #content/api.md
  - Tutorial:
      - Auto Parameters: content/auto_parameters_example.ipynb
