name: dev #  ??? PR -> dev or ??? PR -> staging

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened]
    branches:
      - dev
      - staging

jobs:
  dev-ci-pipeline:
    runs-on: self-hosted-dev
    env:
      NODE_EXTRA_CA_CERTS: /etc/ssl/certs/ca-certificates.crt

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: dev

      - name: Checkout tools repo
        uses: actions/checkout@v2
        with:
          repository: analytics-products-customer360/customer360-dp
          token: ${{ secrets.GH_PAT_ADM }}
          path: actions

      - uses: ./actions/ssh-agent
        with:
          ssh-private-key: |
            ${{ secrets.SEMANTIC_RELEASE_SSH_KEY }}
            ${{ secrets.DEPLOYMENT_HELPER_SSH_KEY }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install pip
        run: |
          pip install pip -U
          pip install pipenv -U
          pip install virtualenv -U

      - name: Install poetry
        uses: ./actions/install-poetry

      - name: Install dependencies and project
        run: |
          poetry env use 3.9
          poetry install -v --without dev,release,docs

      - name: Linting
        run: |
          poetry run pre-commit run --all-files

      - name: Run tests and Check coverage of tests
        run: |
          echo "Launching tests"
          poetry run pytest --cov=src tests/ --cov-fail-under=90
