name: dev # on feature and dev branch

on:
  workflow_dispatch:
  pull_request:
    branches:
      - dev
      - "release/**"

jobs:
  dev-ci-pipeline:
    runs-on: ubuntu-20.04

    steps:
      - name: checkout for PR
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: checkout
        if: github.event_name != 'pull_request'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install pip
        run: |
          pip install --upgrade pip

      - name: Install poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.4.2

      - name: Install dependencies and project
        run: |
          poetry install -v --without interactive,docs

      - name: Linting
        run: |
          poetry run pre-commit run --all-files

      - name: Run tests and Check coverage of tests
        run: |
          echo "Launching tests"
          poetry run pytest --cov=src tests/ --cov-fail-under=90
