name: staging

on:
  workflow_dispatch:
  # pull_request:
  #   types: [closed]
  #   branches:
  #     - staging

jobs:
  staging-ci-pipeline:
    # if: github.event.pull_request.merged == true
    runs-on: ${{ github.event.pull_request.merged && fromJSON('ubuntu-20.04') || 'self-hosted-dev' }}
    env:
      GH_TOKEN: ${{ secrets.GH_PAT }}
      NODE_EXTRA_CA_CERTS: /etc/ssl/certs/ca-certificates.crt

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: dev

      - name: Checkout tools repo
        uses: actions/checkout@v2
        with:
          repository: analytics-products-customer360/customer360-dp
          token: ${{ secrets.GH_PAT_ADM }}
          path: actions

      - uses: ./actions/ssh-agent
        with:
          ssh-private-key: |
            ${{ secrets.SEMANTIC_RELEASE_PRIVATE_KEY }}
            ${{ secrets.UTILS_DATA_LAYER_SSH_KEY }}

      # - uses: fregante/setup-git-user@v1

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install pip
        run: |
          pip install pip -U
          pip install pipenv -U
          pip install virtualenv -U

      - name: Install poetry
        uses: ./actions/install-poetry

      - name: Install dependencies and project
        run: |
          poetry install -v --without dev,release,docs

      - name: Run Intrgration tests
        run: |
          echo "Launching Intrgration tests"
          poetry run pytest tests/ -k 'integration'

      - name: Time for Functional Tests
        run: |
          echo "Time for Functional Tests"
