name: staging

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - staging

jobs:
  staging-ci-pipeline:
    # if: github.event.pull_request.merged == true
    # runs-on: ${{ github.event.pull_request.merged && fromJSON('ubuntu-20.04') || 'self-hosted-dev' }}
    runs-on: self-hosted-dev
    outputs:
      pk_name: ${{ steps.version.outputs.DATAX_REPO_NAME }}
      pk_version: ${{ steps.version.outputs.DATAX_PACKAGE_VERSION }}

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
      DATABRICKS_JOBS_API_VERSION: 2.1 # Use Job API 2.1 instead of 2.0
      GH_TOKEN: ${{ secrets.GH_PAT_ADM }}
      NODE_EXTRA_CA_CERTS: /etc/ssl/certs/ca-certificates.crt

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: staging

      - name: Checkout tools repo
        uses: actions/checkout@v2
        with:
          repository: analytics-products-customer360/customer360-dp
          token: ${{ secrets.GH_PAT_ADM }}
          path: actions

      - uses: ./actions/ssh-agent
        with:
          ssh-private-key: |
            ${{ secrets.SEMANTIC_RELEASE_SSH_KEY }}
            ${{ secrets.UTILS_DATA_LAYER_SSH_KEY }}
            ${{ secrets.DEPLOYMENT_HELPER_SSH_KEY }}

      - uses: ./actions/setup-git-user

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install pip & pex
        run: |
          pip install pip -U
          pip install pipenv -U
          pip install virtualenv -U
          pip install pex

      - name: Install poetry
        uses: ./actions/install-poetry

      - name: Install dependencies and project
        run: |
          poetry config http-basic.pk_repo_prod gh_actions ${{ secrets.AZURE_ARTIFACTS_PAT }}
          poetry install -v --without dev,test,docs
          poetry run pip list --format=freeze --exclude=pip > requirements.txt

      # - name: Semantic Release Prerelease
      #   run: |
      #     poetry run semantic-release publish -D branch="${{ github.event.pull_request.base.ref }}" -D remove_dist=true --prerelease -v DEBUG

      # - name: Sync back to Dev
      #   run: |
      #     git checkout dev
      #     git merge ${{ github.event.pull_request.base.ref }}
      #     git push
      #     git checkout ${{ github.event.pull_request.base.ref }}

      - name: Intrgration Test
        run: |
          echo "Test specific package from prerelease feed"
          echo "DBX deploy"
          echo "Monitoring"

      - name: Build and Upload PEX
        id: version
        run: |
          pk_version=$(poetry version --dry-run -s)
          echo $pk_version
          echo "::set-output name=DATAX_PACKAGE_VERSION::$pk_version"
          pk_name=${{ github.event.repository.name }}
          echo "::set-output name=DATAX_REPO_NAME::$pk_name"
          touch _${pk_name}_${pk_version}.pex
          poetry run az extension add --name azure-devops
          poetry run az artifacts universal publish --organization https://dev.azure.com/dxtechops/ --project="datax" --scope project --feed C360ML --name ${pk_name}_pex --version $pk_version --description "" --path .

# pex -v --requirement=requirements.txt --sources-directory=. --output-file=dist/pex/${pk_name}_${pk_version}.pex --entry-point datax.generic_pipeline.cardx_credit_card -f dist -i https://${{ secrets.AZURE_ARTIFACTS_PAT }}@${{ secrets.PKGS_DL_PROD }} --disable-cache

  staging-cd-pipeline:
    if: ${{ always() }}
    needs: [ staging-ci-pipeline ]
    runs-on: self-hosted-ai-c360stg
    env:
      NODE_EXTRA_CA_CERTS: /etc/ssl/certs/ca-certificates.crt
      resourceGroupName: 'RG-SEA-DATAX-STG-PRD-DP-01'
      databricksWorkspaceName: 'dxdpseaadb001stg'
      keyVaultName: 'KEY-RG-SEA-CTRL-DX​-STG'
      token: ''
        
    steps: 

      - name: Checkout on shared marketplace repo
        uses: actions/checkout@v2
        with:
            repository: 'Share-Module/market-place-module'
            token: ${{ secrets.GH_PAT_ADM }}
            path: actions

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      # - name: Install pip & pex
      #   run: pip install --upgrade pip
      #     pip install pip -U
      #     pip install pipenv -U
      #     pip install virtualenv -U

      - name: Login via Az module
        uses: ./actions/azure-login
        with:
          creds: |
            ${{ secrets.C360_SP_STG }}

      - name: Download secret from KeyVault Secrets
        uses: ./actions/keyvault-module
        with:
          keyvault: ${{ env.keyVaultName }}
          secrets: 'dxdpmlardevopsfrmwk-appid,dxdpmlardevopsfrmwk-secretkey,dxdpmlardevopsfrmwk-tenantid,dxdpmlardevopsfrmwk-subscriptionid'
        id: databricksSecretAction
                
      - name: Generate short life Databricks Token
        run: |
          az logout
          az login \
          --service-principal \
          --username ${{ steps.databricksSecretAction.outputs.dxdpmlardevopsfrmwk-appid }} \
          --password ${{ steps.databricksSecretAction.outputs.dxdpmlardevopsfrmwk-secretkey }} \
          --output table
          echo "DATABRICKS_TOKEN=$(az account get-access-token --resource 2ff814a6-3304-4ab8-85cb-cd0e6f879c1d --query "accessToken" --output tsv)" >> $GITHUB_ENV

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: deploy workflow
        shell: bash
        run: |
          hostname
          echo "${{ needs.staging-ci-pipeline.outputs.pk_name }}${{ needs.staging-ci-pipeline.outputs.pk_version }}"
          echo ${{ env.DATABRICKS_TOKEN }}
          dbx deploy --environment "sit" --deployment-file "./conf/orchestrator/dbx/deployment.yml.j2" --jinja-variables-file "./conf/orchestrator/dbx/inc/*.yml" --no-package
          dbx launch "sit-entrypoint-datax-gp-autox-secure-loan" --environment "sit" --trace

      # - name: Copy init scripts & overwrite
      #  run: |
      #    databricks fs cp -r ./setup/dlt_deployment/init_scripts dbfs:/databricks/scripts/${{ github.event.repository.name }}/init-scripts --overwrite

      # - name: Update the relevant notebook sources
      #   run: |
      #     databricks repos update --path="/Repos/datax-gp-cardx-credit-card/setup/dlt_deployment/notebooks/" --branch="${{ github.event.pull_request.base.ref }}"

      # - name: Job deployment
      #   run: |
      #     poetry run dbx configure --enable-inplace-jinja-support
      #     poetry run dbx deploy --jinja-variables-file=conf/orchestrator/dbx/staging_setting.yml --deployment-file=./conf/orchestrator/dbx/deployment.yml.j2 --workflows=credit-card-workflow,multiple-srcs-workflow --no-package
