name: subdev # for subdev or feat branch, please change the pytest path

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - dev
      - staging
      - main
      - gh-pages
      - "ci/**"
      - "docs/**"

jobs:
  subdev-pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install pip
        run: |
          pip install --upgrade pip

      - name: Install poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies and project
        run: |
          poetry install -v --without release

      - name: Linting
        run: |
          poetry run pre-commit run --all-files

      - name: Run unit tests # change pytest path here
        run: |
          echo "Launching unit tests"
          poetry run pytest tests/datax/utils/deployment_helper/dummy_test/test_dummy.py
