name: workflow_dispatch

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install pip
        run: |
          pip install --upgrade pip
          pip install setuptools wheel twine

      - name: Install poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.6.1

      - name: Install dependencies and project
        run: |
          poetry install -v --without interactive,docs

      - name: Build package
        run: |
          #poetry run setup.py sdist bdist_wheel
          poetry build -f wheel
          poetry run twine upload dist/*
          echo "Building package"
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.AZURE_ARTIFACTS_PAT }}
          TWINE_REPOSITORY_URL: https://pkgs.dev.azure.com/kBank-MDF-SANDBOX/_packaging/kBank-MDF-SANDBOX/pypi/upload
          
      - name: Publish package to Azure Artifact
        run: |
          echo "Publishing package"
