name: Workflow_Check
on:
  #push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]
  workflow_dispatch:

jobs:
  Checkers:

    runs-on: self-hosted-dev #${{ matrix.runner }}
    # strategy:      
    #   matrix:        
    #     runner: [ self-hosted-ai-c360dev, 
    #       self-hosted-ai-c360stg, self-hosted-ai-c360prd, 
    #       self-hosted-dev ]

    env:
      CHECKERS: --webapp-security

    steps:
    - name: Connect to AzDevOps
      run: |
        hostname
        curl https://dev.azure.com
        pip3 uninstall virtualenv
        sudo pip3 uninstall virtualenv
        sudo apt purge python3-virtualenv